version: '3.2'

services:
  gotcourts-checker:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    command:
      - '--mode=service'
      - '--ttoken=${TELEGRAM_TOKEN}'
    restart: always
    deploy:
        resources:
            limits:
              cpus: 0.50
              memory: 512M
            # reservations:
            #   cpus: 0.25
            #   memory: 128M
