FROM python:3.8-slim-buster as builder
RUN mkdir /gotcourts
WORKDIR /gotcourts
ADD gotcourts gotcourts
ADD setup.py setup.py
RUN apt-get update -qq && apt-get install -y build-essential
RUN pip install multidict==4.7.3
RUN pip install .


FROM python:3.8-slim-buster

RUN mkdir /gotcourts
WORKDIR /gotcourts
ADD gotcourts gotcourts
ADD setup.py setup.py
COPY --from=builder /usr/local/lib/python3.8/site-packages /usr/local/lib/python3.8/site-packages
#RUN apt-get update -qq && apt-get install -y build-essential
#RUN pip install multidict==4.7.3
RUN pip install .
ENV PYTHONPATH=/gotcourts/gotcourts:$PYTHONPATH
ENTRYPOINT [ "python", "/gotcourts/gotcourts/run.py" ]
